{{- if and .Values.productionReady.enabled .Values.productionReady.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kranix-operator.fullname" . }}
  labels:
    {{- include "kranix-operator.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.productionReady.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "kranix-operator.selectorLabels" . | nindent 6 }}
{{- end }}
