apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kranix-mcp.fullname" . }}
  labels:
    {{- include "kranix-mcp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kranix-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kranix-mcp.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kranix-mcp.serviceAccountName" . }}
      containers:
        - name: kranix-mcp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
          env:
            - name: READONLY_MODE
              value: {{ .Values.safety.readonlyMode | quote }}
            - name: ALLOW_DELETE_WORKLOAD
              value: {{ .Values.safety.allowDeleteWorkload | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
