apiVersion: v2
name: kranix-mcp
description: Kranix MCP Server
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/kranix-io/kranix
sources:
  - https://github.com/kranix-io/kranix
keywords:
  - kranix
  - mcp
maintainers:
  - name: Kranix Team
    email: team@kranix.io
